# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-27 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patchwork', '0019_userprofile_show_ids'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patch',
            options={'base_manager_name': 'objects', 'verbose_name_plural': 'Patches'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ('date',), 'verbose_name_plural': 'Series'},
        ),
        migrations.AddField(
            model_name='project',
            name='subject_prefix',
            field=models.CharField(blank=True, help_text=b'An optional prefix that mail subject must match. This allow to handle multiple project under the same list ID', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='listid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('listid', 'subject_prefix')]),
        ),
    ]
